### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by andreltr** [beacoder/stock-tracker#9]
Hello,

I'm receiving an error while fetching the US stock data. AFAIK, the error regards the json-read function. See below please.

Fetching stock data ...
json-read: End of file while parsing JSON

My .emacs file (part of it),

;; Stock tracker
(add-to-list 'load-path "~/.emacs.d/stock-tracker/stock-tracker.el")
(require 'stock-tracker)

;; Refresh stock price every 5*10 secs
(customize-set-variable 'stock-tracker-refresh-interval 5)

;; Set up as green, down as red
(customize-set-variable 'stock-tracker-up-red-down-green nil)

;; Customize stocks
(customize-set-variable 'stock-tracker-list-of-stocks
                        '("BBAS3.SA" "KLBN4.SA" "CXSE3.SA" "PETR4.SA" "TAEE3.SA" "CMIG3.SA"))

;; Example Key binding
(global-set-key (kbd "C-c s") 'stock-tracker-start)

Any help appreciated,

Andre Luiz

**Comment by beacoder** [comment]
Hi,
I'll try to reproduce with your configuration first, and see if I can find
anything.
thanks.

andreltr ***@***.***> 于2024年5月23日周四 23:00写道：

**Comment by beacoder** [comment]
<img width="701" alt="Capture" src="https://github.com/beacoder/stock-tracker/assets/3895681/60011e63-0129-4c00-aafa-aef124e726b8">

Hi,

it works fine in my emacs, not sure what your problem is.

you could use the following elisp code to check whether the received the stock data is valid or not.

(cl-assert (stock-tracker--request-synchronously "BBAS3.SA" (make-stock-tracker--us-symbol)))

thanks.

**Comment by andreltr** [comment]
Thanks! I'll try that out and return its answer to you.

**Comment by andreltr** [comment]
> Thanks! I'll try that out and return its answer to you.

Hello,

I fixed the issue. It was due to another configuration in my .emacs file.
However, I'd like to change from the green color which I find too bright on my notebook to a lower intensity green and/or red color.  I guess it might be related to the stock-tracker-up-red-down-green variable.  How can that be done, please?

TIA

**Comment by beacoder** [comment]
<img width="859" alt="Capture" src="https://github.com/beacoder/stock-tracker/assets/3895681/c69d025f-8e46-4bd5-9944-be2f9f940ea7">
I'm afraid you're gonna have to change this part of code by yourself.

Brs/Humingc

**Comment by andreltr** [comment]
Done. Thanks!

**Comment by beacoder** [comment]
welcome ~

Brs/Humingc

andreltr ***@***.***> 于2024年5月27日周一 11:07写道：
